services:
  - type: web
    name: roig-arena
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile.render
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: RoigArena
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
